# fly.toml app configuration file generated for love-photos-back on 2025-06-22T21:51:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'love-photos-back'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[experimental]
  vm_size = "shared-cpu-1x"



# Environment variables for the application
[env]
  # Application
  NODE_ENV = "production"
  PORT = "3000"
  
  # Database
  MONGODB_URI = "mongodb+srv://matheusschmidt05:pvRhgrGOnNqDe2w5@lovephotos.bj9uk4z.mongodb.net/?retryWrites=true&w=majority&appName=LovePhotos"
  

# imgur API credentials
IMGUR_API_URL="https://api.imgur.com/3/image"
IMGUR_CLIENT_ID="db60dcc9f0a8252"
CLIENT_SECRET="e6ee3c141e3bc3061db94fa9647aa04488718066"
  
  

# Health check configuration
[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

  [checks.ready]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false


